# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: "aabs"
    replace: "Abs,\nNicholas ºLº,"

  - trigger: "aass"
    replace: "Qualquer dúvida, estou à disposição\nAbs,\nNicholas"

  - trigger: "ccheck"
    replace: "✔️"

  - trigger: "wwrong"
    replace: "✖️"

  - trigger: "==>"
    replace: "→"

  - trigger: "<=="
    replace: "←"

  - trigger: "==^"
    replace: "↑"

  - trigger: "==v"
    replace: "↓"

  # ASC II Icons & Symbols
  - trigger: ":wtf"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":ye"
    replace: "ᕙ(ºL,º)ᕗ"

  - trigger: ":fuck"
    replace: "(⋟﹏⋞)"

  # Dates
  - trigger: "ddate"
    replace: "{{ndate}}"
    vars:
      - name: ndate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: "fdate"
    replace: "{{fdate}}"
    vars:
      - name: fdate
        type: date
        params:
          format: "%Y.%m.%d"

  # HTML
  - trigger: ">>html"
    replace: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://unpkg.com/modesto@latest/modesto.min.css">

      <title></title>
      </head>
      <body>
      $|$
      </body>
      </html>
  
  - trigger: ">>modesto"
    replace: "<link rel=\"stylesheet\" href=\"https://unpkg.com/modesto@latest/modesto.min.css\">\n"

  # Shell commands
  - trigger: ">>shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"